project_id = "somnrhvcmlotspyzpxpp"

[functions.alpha-vantage-quote]
verify_jwt = false

[functions.alpha-vantage-stocks]
verify_jwt = false

[functions.alpha-vantage-news]
verify_jwt = false

[functions.alpha-vantage-nasdaq]
verify_jwt = false

[functions.generate-recommendations]
verify_jwt = false